name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Ubuntu
        run: |
          ls 
          docker compose up --build -d